<a href="https://colab.research.google.com/github/Seixaslima/curso_python_pandas/blob/main/segundo_dia_codigo_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

primeiro codigo de manipulação de dados com **python panda** \\
**Autor:** Lucas Seixas \\
**Data:** 07/02/2023

In [23]:
#Importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_csv("drive/MyDrive/python-pandas/precos-semestrais-ca-2022-01.csv",sep=";",decimal=',')

Comandos para visualizar a base de dados

print - nativo do python \\
display - mostra mais organizado \\

In [ ]:
print(combustiveis_df)

In [ ]:
display(combustiveis_df)

In [ ]:
#mostra as 5 primeiras linhas
display(combustiveis_df.head())

In [ ]:
#mostra as 15 primeiras linhas ao invez das 5
display(combustiveis_df.head(15))

In [10]:
#dataframe.shape mostra o numero de (linha, coluna)  dataframe.describe

print(combustiveis_df.shape)

(529424, 16)

In [ ]:
print(combustiveis_df.describe())

In [24]:
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529424 entries, 0 to 529423
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     529424 non-null  object
 1   Estado - Sigla     529424 non-null  object
 2   Municipio          529424 non-null  object
 3   Revenda            529424 non-null  object
 4   CNPJ da Revenda    529424 non-null  object
 5   Nome da Rua        529424 non-null  object
 6   Numero Rua         529211 non-null  object
 7   Complemento        113936 non-null  object
 8   Bairro             527991 non-null  object
 9   Cep                529424 non-null  object
 10  Produto            529424 non-null  object
 11  Data da Coleta     529424 non-null  object
 12  Valor de Venda     529424 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  529424 non-null  object
 15  Bandeira           529424 non-null  object
dtypes: float64(2), object(14)
memory usage: 64.6+ MB
None

In [ ]:
#filtrar apenas uma coluna
display(combustiveis_df['Produto'])

In [27]:
#cria um novo dataFrame com os filtros aplicados
ca_df = combustiveis_df[['Municipio','Revenda','Produto','Valor de Venda']]
display(ca_df)

,Municipio,Revenda,Produto,Valor de Venda
0,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,GASOLINA,6.99
1,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,ETANOL,5.99
2,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,DIESEL,6.09
3,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,GASOLINA ADITIVADA,7.05
4,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,DIESEL S10,6.12
...,...,...,...,...
529419,CUIABA,OZ REVENDEDORA DE COMBUSTIVEIS LTDA,GASOLINA,6.49
529420,CAXIAS,POSTAO COMERCIO DE COMBUSTIVEIS LTDA,GASOLINA ADITIVADA,6.99
529421,CAXIAS,POSTAO COMERCIO DE COMBUSTIVEIS LTDA,DIESEL S10,7.59
529422,CAXIAS,POSTAO COMERCIO DE COMBUSTIVEIS LTDA,DIESEL,7.55
529423,CAXIAS,POSTAO COMERCIO DE COMBUSTIVEIS LTDA,GASOLINA,6.99

In [28]:
#exibir a linha escolhida .loc[]

display(ca_df.loc[4])

Municipio                        RIO BRANCO
Revenda           AUTO POSTO AMAPA - EIRELI
Produto                          DIESEL S10
Valor de Venda                         6.12
Name: 4, dtype: object

In [29]:
#exibir um intervalo de linhas escolhidas

display(ca_df.loc[9:19])

     Municipio                    Revenda             Produto  Valor de Venda
9   RIO BRANCO     AUTO POSTO ACAUAN LTDA          DIESEL S10            6.12
10  RIO BRANCO  AUTO POSTO CORRENTAO LTDA            GASOLINA            6.98
11  RIO BRANCO  AUTO POSTO CORRENTAO LTDA              DIESEL            6.08
12  RIO BRANCO  AUTO POSTO CORRENTAO LTDA  GASOLINA ADITIVADA            7.08
13  RIO BRANCO  AUTO POSTO CORRENTAO LTDA          DIESEL S10            6.13
14  RIO BRANCO    AUTO POSTO CANINDE LTDA            GASOLINA            6.98
15  RIO BRANCO    AUTO POSTO CANINDE LTDA              DIESEL            6.05
16  RIO BRANCO    AUTO POSTO CANINDE LTDA  GASOLINA ADITIVADA            7.13
17  RIO BRANCO    AUTO POSTO CANINDE LTDA          DIESEL S10            6.09
18  RIO BRANCO         POSTO BATISTA LTDA            GASOLINA            6.87
19  RIO BRANCO         POSTO BATISTA LTDA          DIESEL S10            5.99

In [31]:
#filtra o dataframe de acordo com certos parametros celecionados
#filtramos o DF que o produto é gasolina
#e colocamos as colunas Municipio, Revenda, Produto, Valor de Venda

gas_df = ca_df[ca_df['Produto'] == 'GASOLINA']

display(gas_df)

display(gas_df.max())

,Municipio,Revenda,Produto,Valor de Venda
0,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,GASOLINA,6.99
5,RIO BRANCO,AUTO POSTO ACAUAN LTDA,GASOLINA,6.99
10,RIO BRANCO,AUTO POSTO CORRENTAO LTDA,GASOLINA,6.98
14,RIO BRANCO,AUTO POSTO CANINDE LTDA,GASOLINA,6.98
18,RIO BRANCO,POSTO BATISTA LTDA,GASOLINA,6.87
...,...,...,...,...
529408,DIVINOPOLIS,AUTO POSTO CENTENARIO LTDA.,GASOLINA,7.19
529411,MOGI GUACU,DUAS AVENIDAS DE MOGI GUACU POSTO DE SERVICOS ...,GASOLINA,5.99
529416,IRECE,AUTO POSTO NORDESTE LTDA,GASOLINA,7.94
529419,CUIABA,OZ REVENDEDORA DE COMBUSTIVEIS LTDA,GASOLINA,6.49
529423,CAXIAS,POSTAO COMERCIO DE COMBUSTIVEIS LTDA,GASOLINA,6.99

Municipio                               XINGUARA
Revenda           ÁGUAS LINDAS COMBUSTÍVEIS LTDA
Produto                                 GASOLINA
Valor de Venda                              8.99
dtype: object